Initial dracut overlay files
SUSE-Enceladus/google-dracut-config pull request #1
Opened 2024-12-02 22:35 UTC by smarlowucf

2024-12-03 09:51 UTC, apozsuse commented on etc/dracut.conf.d/07-aws-type-switch.conf
> +add_drivers+=" ena xen-blkfront xen-netfront "
should this `aws` file be included in google's config? :thinking:

2024-12-03 12:18 UTC, rjschwei commented on etc/dracut.conf.d/07-aws-type-switch.conf
> +add_drivers+=" ena xen-blkfront xen-netfront "
This is not needed in Google, there is no Xen, please remove.

2024-12-03 12:19 UTC, rjschwei requested changes

2024-12-03 12:19 UTC, rjschwei commented on google-dracut-config.spec
> +%config %{_sysconfdir}/dracut.conf.d/07-aws-type-switch.conf
Drop this

2024-12-03 12:19 UTC, rjschwei commented on google-dracut-config.spec
> +    %{buildroot}%{_sysconfdir}/dracut.conf.d/07-aws-type-switch.conf
Drop this, only applies to AWS

2024-12-03 19:00 UTC, rjschwei approved these changes

2024-12-03 19:26 UTC, merged

2024-12-04 11:20 UTC, jgleissner commented
Hi, sorry I'm a bit late to this, but IMO packages shouldn't install into `/etc` unless absolutely necessary. Dracut supports `/usr/lib/dracut/dracut.conf.d` so that's where the files should go.

2024-12-04 16:44 UTC, smarlowucf commented
> Hi, sorry I'm a bit late to this, but IMO packages shouldn't install into `/etc` unless absolutely necessary. Dracut supports `/usr/lib/dracut/dracut.conf.d` so that's where the files should go.

Okay, I will submit PRs with the changes.