Move dracut files to usr lib
SUSE-Enceladus/google-dracut-config pull request #2
Opened 2024-12-04 20:21 UTC by smarlowucf

2024-12-05 10:06 UTC, apozsuse approved these changes
LGTM

2024-12-05 11:22 UTC, jgleissner requested changes

2024-12-05 11:22 UTC, jgleissner commented on google-dracut-config.spec
> +%config /usr/lib/dracut/dracut.conf.d/11-resume.conf
Those files shouldn't be marked as `%config`  as they are not intended to be altered.

2024-12-05 12:18 UTC, rjschwei requested changes

2024-12-05 12:18 UTC, rjschwei commented on google-dracut-config.spec
> +    %{buildroot}/usr/lib/dracut/dracut.conf.d/11-resume.conf
Please use `%_libdir` macro

2025-01-06 18:12 UTC, smarlowucf commented
rebased and merged the config macro change

2025-01-07 08:09 UTC, jgleissner requested changes

2025-01-07 08:09 UTC, jgleissner commented on google-dracut-config.spec
> +%{_libexecdir}dracut/dracut.conf.d/11-resume.conf
As mentioned in https://github.com/SUSE-Enceladus/microsoft-dracut-config/pull/2, `%_libexecdir`  expands to `/usr/libexec` on some distros and is intended for executables used indirectly. This should be `%_libdir` or `/usr/lib`, at least until the dracut package gets changed to use `/usr/etc`.

2025-01-07 19:22 UTC, smarlowucf commented on google-dracut-config.spec
> +%{_libexecdir}dracut/dracut.conf.d/11-resume.conf
Fixed. Using full path instead

2025-01-07 20:48 UTC, rjschwei approved these changes

2025-01-07 21:33 UTC, jgleissner approved these changes

2025-01-08 16:06 UTC, merged